### ISSUE TITLE
TOTK research: Key item limits

### ISSUE THREAD

**Issue by Titanor-Soulstone** [marcrobledo/savegame-editors#180]
i just discovered Zonaite goes over 10000 and Crystallized Charge goes over 1000

I will keep searching for items that go over 999

**Comment by HylianLZ** [comment]
Poes do too. The key item. internal name MinusRupee_00

**Comment by marcrobledo** [comment]
> Poes do too. The key item. internal name MinusRupee_00

So... Poes go over 1000 or 10000?

**Comment by gavincheang** [comment]
As I know Poes, Zonaites, Large Zonaites, Crystallized Charge maximum limits should be 999999

**Comment by ApacheThunder** [comment]
Does setting Travel Medallion beyond 3 work? I'm curious about that and how the game handles it.

**Comment by Titanor-Soulstone** [comment]
zonaite can go above 100,000 as well as large zonaite

**Comment by ApacheThunder** [comment]
Rather then create a new issue I'll post about it here but reporting that adding new paraglider cloths to key items menu doesn't result in them being usable when you talk to the NPC to switch them out. Ones added via save editor don't show up.

Don't recall if this is normal behavior or not but all existing cloths vanish from key items menu after interacting with NPC. But I double checked before the save edit and saw that my current cloth which is the skyward sword one isn't currently in my key items menu and it's been quite awhile since I've talked to him to switch it out so them vanishing from key items menu may be a normal behavior of the game. (aka they get transferred to a new menu used by the NPC)

Anyways the game has something extra going on with these paraglider cloth key items that the NPC menu is rejecting for some reason so add that to the todo list. ;)

**Comment by marcrobledo** [comment]
> Rather then create a new issue I'll post about it here but reporting that adding new paraglider cloths to key items menu doesn't result in them being usable when you talk to the NPC to switch them out. Ones added via save editor don't show up.
> 
> Don't recall if this is normal behavior or not but all existing cloths vanish from key items menu after interacting with NPC. But I double checked before the save edit and saw that my current cloth which is the skyward sword one isn't currently in my key items menu and it's been quite awhile since I've talked to him to switch it out so them vanishing from key items menu may be a normal behavior of the game. (aka they get transferred to a new menu used by the NPC)
> 
> Anyways the game has something extra going on with these paraglider cloth key items that the NPC menu is rejecting for some reason so add that to the todo list. ;)

Yeah, I'm pretty sure it probably requires some extra flags to be enabled.
As I have stated in other issues, I currently have no time to datamine the game files. If someone else does the dirty job before me and shares the savegame hash keys, we will be able to edit literally everything.
