### ISSUE TITLE
TOTK: Weapon Durability seems to reset in game

### ISSUE THREAD

**Issue by OhNoOhNOOO** [marcrobledo/savegame-editors#184]
Might be caused by a check within the game itself, but weapon durability seems to change back from whatever absurd amount its been changed to back to the weapon's original maximum durability after a single use in game.

**Comment by Haste76** [comment]
True, this happens to me too. I add 10000000 or 800 like the Hylian Shield durability though as soon as I go in game everything else is fine but any item with durability increased goes back to the standard one. It doesn't matter if it's fused or standard. I tried it on the Master Sword with a fuse, Sea Breeze Shield fused with another Sea Breeze Shield, Dusk Bow and standard Hylian Shield

**Comment by marcrobledo** [comment]
This was explained in #178.
TOTK changed how durability works and you cannot set a higher value than its base durability anymore like in BOTW. The game resets the value as soon as you load your save. If you want to have infinite durability, you will have to use RAM cheats or ROM modding.
Developers might have done this on purpose to block cheats with savegame editing or, maybe it was just a decision made due to how weapons fuse feature work.

Since this seems to be a recurrent question. I'll add a Restore weapons button that sets all your weapons to its maximum value. It's all we can do.

**Comment by marcrobledo** [comment]
The restore durability icon was added.
