### ISSUE TITLE
TOTK - Restore Durability Button

### ISSUE THREAD

**Issue by Camansur** [marcrobledo/savegame-editors#204]
The new "weapon/bow/shield/armor add button" replaced the restore durability button. It would be better to leave the restore durability along side the new button. Unless this is somewhere else now that i'm not aware of.

**Comment by GhStRdR2k** [comment]
I agree, would much rather have the restore durability button back. I had a bunch of weapons that needed repair and was like "wait...where'd the button go?"

**Comment by marcrobledo** [comment]
You can now edit the durability manually (just type a big value and it will reset to the base durability)...
Or... Set the Durability Up modifier and a high value to make it almost infinite!

**Comment by Camansur** [comment]
I have been doing that but I find it quite repetitive having to do it for every single weapon. Especially if I'm not sure which weapon is degraded since I don't know exactly what the maximum durability is until I enter a large value.

**Comment by love768952693** [comment]
May I ask everyone, can you modify the quantity of food you cook? I cannot modify many of them, only a few can.

**Comment by Camansur** [comment]
> I would like to ask everyone, can the amount of food you cook be modified? I can't do many, only a few can be modified.

Foods do not stack by default I think. When you modify the value, it will not show in the inventory, but if you eat the food then change tabs or close and re-open the inventory, you will find that it reappears.

**Comment by M1CR0H4CK3R** [comment]
> You can now edit the durability manually (just type a big value and it will reset to the base durability)... Or... Set the Durability Up modifier and a high value to make it almost infinite!

As far as I can tell, setting Durability ↑↑ doesn't add the new durability to the weapon automatically, nor is the new maximum durability accounted for after changing the Modifier Value to, say, 500, e.g. you still cannot set the durability to 535 for a Savage Lynel Bow, even with 500 boosted durability. I am forced to hex edit my save file in order to properly set the durability, which isn't ideal, as I need to compare minor changes in the file, which takes a long while.

**Comment by marcrobledo** [comment]
The restore durability button is also back ;-)
