### ISSUE TITLE
HASHS FROM KOROKS SEEDS AND SHRINES TOTK

### ISSUE THREAD

**Issue by DaviF19** [marcrobledo/savegame-editors#225]
Post in thread 'zelda tears of the kingdom 152 shirne+120 tree+800 korok save' https://gbatemp.net/threads/zelda-tears-of-the-kingdom-152-shirne-120-tree-800-korok-save.633097/post-10164724

please have a look at this thread and this GBAtemp post, it has all the koroks and shrines hashes, this may help save time and inclement them to the editor 

We appreciate your work, it's amazing, so if you can do this inclementation that would be great

**Comment by marcrobledo** [comment]
Unfortunately, that list does not seem very accurate.
It's got 883 korok hashes (should be 900) and like 1400+ shrine hashes.

Those hashes are easily found in the game files and I got all of them already myself some days ago. However, without their original key names, it's just some random numbers that might or might not be related to korok or shrines.
I'm cautious and I do not want to implement unreliable features to the editor because that would lead to changing undesired values (and to users complains as well after realizing they cannot progress in-game, etc).
