### ISSUE TITLE
TOTK: Weapon/bow durability broken

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#234]
I've just started using this editor but i think the weapon durability is broken.
If i try changing durability of something it's locked to the current value. If i change modifier to any of the durability options both the durability value and modifier value shoots up to 2100000000, I'm able to change it to a lower value but i can't see the original value anywhere and if i press 'restore durability' it goes right back to 2100000000.
If i change the modifier value to 0 it doesn't do anything and if i change it to 1+ it starts adding from the default value used in 'no bonus' so it's impossible to tell what the normal value for durability 1 and durability 2 is.

Also, any weapon added starts with 4294967295 as modifier value, but when you switch to durability it gets corrected to what seems to be its max value of 2100000000 on both fields, so that starting value might be the issue.

**Comment by marcrobledo** [comment]
There is no normal value for Durability modifier. The game generates a random modifier value when it creates a new weapon. I don't know the range because I haven't found a weapon with a durability modifier yet in-game.

**Comment by marcrobledo** [comment]
Durability↑ and Durability↑↑ exist because they are different tier modifier.
As far as I know, you cannot legitly get a modifier tier 1 (white) until you progress in the story. Then, the modifier tier 2 (golden) appear much later in the game.
The difference between the two of them is probably the effectiveness. A weapon with Durability↑↑ with the same modifier value as a Durability↑ will probably last much longer. I haven't tested this myself, but I'm pretty sure that's how the game works.

The restore durability button will set the weapons' durability to their allowed maximum depending on their modifier. That's it:
- if the weapon has any modifier but Durability, it will set the current durability it to the default base value
- if the weapon has Durability set, it will set it to Modifier value+Durability base

Oh, by the way, that 2100000000 is intended. I made it that way so every time you set a durability modifier, it automatically sets the modifier value to that high value. I was getting too many complains about users not being able to create infinite weapons anymore like in BOTW (which is not an issue of the editor but a game design decision). That mitigated it fortunately.

**Comment by JimZiii** [comment]
That actually makes sense. My bad then 😂 thnx for explaining it

**Comment by marcrobledo** [comment]
No worries :-)
If you don't like those huge values, just set the modifier value to 40 or 50 (I guess that would be a legit value) then use the Restore durability button, it will set that weapon durability to base weapon durability+modifier value.
