### ISSUE TITLE
TOTK: master sword not showing up in-game

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#239]
I changed a current weapon to the normal master sword with durability bonus, but when i open the game the slot is empty.
But if i open the save in the editor it's still there.

Am i doing something wrong?

**Comment by Lucifiish** [comment]
This is because it's flag based and you can not use it in-game between when you lose it on the altar and when you obtain it properly. There is a separate weapon in the save editor called "Master Sword (Glitched)." If you add it in that way, it will work.

Not a necessary step, but I felt I'd share should you be interested - Try making a weapon fusion in-game then setting that fusion to "Master Sword (Glitched)." It has some pretty fun results

**Comment by Lucifiish** [comment]
This issue can be closed!

**Comment by JimZiii** [comment]
> This is because it's flag based and you can not use it in-game between when you lose it on the altar and when you obtain it properly. There is a separate weapon in the save editor called "Master Sword (Glitched)." If you add it in that way, it will work.
> 
> Not a necessary step, but I felt I'd share should you be interested - Try making a weapon fusion in-game then setting that fusion to "Master Sword (Glitched)." It has some pretty fun results

I suspected that was the issue but wasn't sure. And i didn't know what the glitched version.
Thnx for the help and fusion tip, I'll try it out
