### ISSUE TITLE
TOTK: Stuck in Crisis at Hyrule Castle because Purah doesn't give me paraglider

### ISSUE THREAD

**Issue by humongous74** [marcrobledo/savegame-editors#246]
Just like the title says I get to Purah in the skyview tower after speaking to the captain (in the Crisis at Hyrule caste quest), she tells me to hold the pad over the terminal but nothing happens. I don't get a paraglider even though I went back to the save editor and had all my paragliders deleted. I'm basically stuck here and can't go anywhere else. Can somebody help me with this or do I need to start the game all over again? Thank you in advance.

**Comment by Lucifiish** [comment]
To clarify, are you saying you’re not getting a functioning paraglider, or that you can’t put the purah pad on the terminal to activate the towers cutscene?

If it’s the former, that is a save editing bug, albeit an obscure one - while Marc might be able to fix your file, restarting is your best bet.

If it’s the latter, it’s probably an emulator issue - there’ve been lots of reports of the A button not working for runes/certain actions on Yuzu and Ryujinx. If you’re not using an emulator, I’m not sure.

I would back up your saves to a zip file and try a fresh save - if that solves the issue, it’s a save bug; otherwise, reach out based on emulator/hardware

**Comment by humongous74** [comment]
I can’t put the purah pad on the terminal to activate the towers cutscene. I stand in front of the terminal and nothing happens.

**Comment by humongous74** [comment]
I'm on a Mariko Switch.

**Comment by Lucifiish** [comment]
> 

What is a Mariko Switch?

**Comment by humongous74** [comment]
yes, a hardware modded switch (not oled/lite)

**Comment by marcrobledo** [comment]
I suppose you used the editor before you got stuck. Do you remember which edits did you do?

Messing with key items is very dangerous. This is the biggest issue of using cheats and/or editing saves, there might be unknown side effects. Always use them on your own responsibility and keep a backup of your savegames before editing.

**Comment by djwyman** [comment]
So I had just run into this issue.  The fix for this issue is to go into the save game editor again, then go to master editor.  Once there, go to the tower section and deselect the first tower for all 3 selections. Then save.  After that, you can complete this part of the game.

**Comment by marcrobledo** [comment]
Nice @djwyman ! Thank you for the solution.

I'm closing the issue, but your message will be kept here just in case anyone else runs across this bug.
