### ISSUE TITLE
TOTK request: Add All Recipes Feature

### ISSUE THREAD

**Issue by Dominic-Dom** [marcrobledo/savegame-editors#279]

**Comment by JimZiii** [comment]
Maybe im wrong but wouldnt that flood your recipe list completely?
Just using 2 materials there's 64 recipes since you can cook it alone, with 1 of the other material, with 2, 3, 4. Then cooking 2 of that material alone, then with 1 of the other material, 2, 3... and so on..
And you can mix and match almost anything so there's a ridiculous amount of recipes, it works probably be unusable tbh
