### ISSUE TITLE
TOTK RIP marker deletion

### ISSUE THREAD

**Issue by RokkumanX** [marcrobledo/savegame-editors#291]
Hello and thank you for a very good editor for TOTK!

Would it be possible to implement an option to remove the RIP marker on the map?
Unlike BOTW which I think removed it after a while, TOTK does not and I have been playing for well over 100+ hours and I made a cheap death right in the beginning and have been reminded of it since.

Completing the game does nothing either, nothing works and it's always there.

A big thanks in advance and have a awesome day.

**Comment by AssGman** [comment]
Interesting idea actually, there is a lot of talk and requests for pretty much everything related to TotK but nothing that mentions the R.I.P markers on the map.

I don't know if this would be possible or not since I'm guessing the markers are on different locations all the time but I too am interested in this.

**Comment by marcrobledo** [comment]
We should start by checking if the death marker is in `progress.sav` or `footprint.sav`.

We might be able to guess just by replacing the `footprint.sav` with another one without a single death. Does anyone want to try it?

**Comment by AssGman** [comment]
I will finally have some time tomorrow over for playing the game so I would be more than interested in trying switching out the footprint.sav as it's so easy just restore it from a backup if it doesn't work.

Anything else that is worth trying out?

**Comment by AssGman** [comment]
OK, I managed to get my R.I.P marker to be deleted by doing this:

1. I started a new game

2. I played the prologue until the very moment you awaken in the Great Sky Island and then made a manual hard save

3. I replaced the caption.sav, direct_file_save_related.sav and the footprint.sav in my completed manual hard save with the ones from the new manual hard save and left the progress.sav completely intact

4. When I loaded the completed game with this Frankenstein save it looked like it was still the new game save but when I got into the game I was still in Lookout Landing with all my Hero Path erased including the R.I.P marker

So it looks like my slate was wiped cleaned and I can continue to play the rest of the game without that marker, don't know what else this effects but all my stuff is there so profit!?!

**Comment by marcrobledo** [comment]
Nice!

As I expected, the death marker was loaded from `footprint.sav` (which contains all data for Hero Path).

The only issue is that you lose the Hero path information in your savegame :-(

Would it be possible to edit that value in `footprint.sav`? Yes, but doesn't sound like a priority, as researching that file could take some time.

**Comment by AssGman** [comment]
Well, I have been playing around for a bit and other then that a couple of album pictures got whacked (nothing of importance) and my Hero Path got reset everything is working perfectly OK as my compendium is 100% complete and intact.

Seems it only reverted the album pictures Zelda took in the prologue to stock.

I realize that replacing the footprint.sav only would probably have sufficed, but oh well, the marker is gone.

**Comment by tari** [comment]
It's certainly too late to help with this request, but I've reverse-engineered the point data in footprint.sav and can say that ensuring the death flag (bit 1) in each point is clear may clear the RIP marker from the map: https://www.taricorp.net/2023/totk-footprints/#complete-data-format

I say it may, since it's possible the last death is also stored in the file header for quick lookup and would also need to be edited; I haven't investigated that at all but it wouldn't be difficult to check.
