### ISSUE TITLE
TOTK: SavegameEditor.readString64 behaves as if they were null-terminated

### ISSUE THREAD

**Issue by lhecker** [marcrobledo/savegame-editors#305]
I noticed that if I load a save file and export it again, some binary differences appear to happen.

Save files appear to store 0x40 byte long item names that might look like this:
```
Item_Ore_G␀191␀3␀␀␀␀␀␀␀␀...
```

Because `MarcFile.prototype.readString` stops reading once it encounters the first null byte, the JS loader turns this into:
```js
"Item_Ore_G"
```

Once it exports the string, the trailing `␀191␀3` are lost. Is this information not relevant to TOTK? I would guess it might be safer to read the item names in their entirety as a 40-character long string for the `id` and split off the first non-null part for any string lookups.

In my personal opinion I think `MarcFile.prototype.readString` might be renamed to something that reflects that it behaves asymmetrical to `writeString` (which doesn't terminate on the first null character). For instance, `readNullTerminatedString`. But I'd understand if the renaming would be a bit of a hassle.

In any case I imagine the solution would be something like this:
```js
MarcFile.prototype.readStringBlock = function(a, b) {
	for (var c = "", d = 0; d < b && a + d < this.fileSize; d++)
		c += String.fromCharCode(this._u8array[a + d]);
	return c
}

SavegameEditor={
	readString64:function(hashKey, arrayIndex){
		if(typeof arrayIndex==='number')
			return tempFile.readStringBlock(SavegameEditor.Offsets[hashKey] + 0x04 + arrayIndex*0x40, 0x40);
		return tempFile.readStringBlock(SavegameEditor.Offsets[hashKey], 0x40);
	},
	getFirstString64:function(str){
		const idx = str.indexOf('\0');
		return idx === -1 ? str : str.substring(0, idx);
	}
}
```

and the various item/equipment/etc. files would need to be updated to use the readString64 outputs for `id` storage and `getFirstString64` for a later lookup in the various lookup tables.

I'd be happy to write a PR for this, but opened this issue to discuss whether this is a real concern and if the above would be an acceptable approach if it is.

**Comment by marcrobledo** [comment]
About this:

```
Item_Ore_G␀191␀3␀␀␀␀␀␀␀␀...
```

This happens when the game replaces an item with another one in the pouch. It just writes the new item ID in the same offset so, if the new item ID is shorter than the old one, there will be leftovers of the old one there.

But since \0 character is the end of string, the game just reads `Item_Ore_G`. The other characters are ignored and will be probably replaced sooner or later by another larger item ID as soon as the player messes with items.

So, the editor is reading the item IDs just like the game, it's fine as it is.


However there is another thing related to this that I was aware already: the `writeString`. My code always fill with \0s after writing a string, 'killing' those string leftovers. It's not a problem because the game just reads until it finds the end of string character \0 (just as any string parser if you ask me), so it doesn't matter if it has more zeroes after that. But it is true that even if you don't do any edit in the editor, the the savegame file might end up being different than the original one.
It is not anything important though.

**Comment by ApacheThunder** [comment]
I can concur on that behavior. I have been seen left over actor ID names in the Autobuilder data so yeah looks like the game just sets 00 to end a string and doesn't bother deleting bytes after that since the game wouldn't read them past the 00.

**Comment by lhecker** [comment]
Oh wow, that makes a ton of sense! Thank you so much for the fantastic explanation!
I'll edit the title of the PR so that anyone else with the same question might find it. 🙂
