### ISSUE TITLE
TotK: Possible to Edit Key Items Amounts?

### ISSUE THREAD

**Issue by NateHevens** [marcrobledo/savegame-editors#314]
I notice that I can add the Light of Blessing and Korok Seeds, but I can't edit how many I have. Is this not possible, yet, or can it be changed so we can change the amount of Key Items we have?

**Comment by marcrobledo** [comment]
Fixed in 74cbcc8!

**Comment by Skorfius** [comment]
Nice update it seems to have been improved drastically.
However please note that when adding in items to a save with no key items it will still generate the first item with a editable value and in this case its the purah pad sadly haha
If you however add an item in the editor after the last available key item this being Addisons fabric atm, that'll give u the purah pad and it does not have an editable value so it seems like its exclusive to only the first item added via editor.
On that note you can still swap key items with editable values such as (poes) with an item that should not have multiples.

This is really just nitpicking tbh, I find it is more than usable as it is now and I don't really see the need to fix it. Just thought I'd let you know if u ever feel like changing it.

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
