### ISSUE TITLE
TOTK: Export/Import of Map Pins

### ISSUE THREAD

**Issue by Truinto** [marcrobledo/savegame-editors#320]
Button to export the non-free map pins to a file. Preferable in a human readable format (not binary). Just a list separated by tabulators and new-lines would be enough. Or xml/json/yaml, whatever is easiest.
Button to import map pins from a file and merge them with existing pins.

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
