### ISSUE TITLE
TOTK: Bubbulfrogs not marked as complete

### ISSUE THREAD

**Issue by EricKirschenmann** [marcrobledo/savegame-editors#323]
I've completed every bubbulfrog and gotten the reward and ending for Koltin, however when I load my save in the save editor it shows only 144/148 bubbulfrogs completed. I'm not sure what the issue is.

**Comment by EricKirschenmann** [comment]
I tested the mark bubbulfrog locations on the map and it marked 4 chasms not bubbulfrogs or caves. So I think it's definitely looking at the wrong thing in regards to bubbulfrogs. 

Currently on v1.1.1 for reference.

**Comment by KingdombeastXx** [comment]
@EricKirschenmann Not sure if you are still having this problem but I had it too. The one I was missing was the Komo Shoreline Cave. There is the link down below.

https://mapgenie.io/zelda-tears-of-the-kingdom/maps/hyrule?locationIds=281708

**Comment by KingdombeastXx** [comment]
@EricKirschenmann Not sure if you are still having this problem but I had it too. The one I was missing was the Komo Shoreline Cave. There is the link down below.

https://mapgenie.io/zelda-tears-of-the-kingdom/maps/hyrule?locationIds=281708

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
