### ISSUE TITLE
TOTK: Feature request delete added armor 

### ISSUE THREAD

**Issue by bauch1234** [marcrobledo/savegame-editors#332]
Feature request to delete armor for if you get duplicates after adding some in the save editor then getting them in game

**Comment by ChaoticG** [comment]
I don't think it's worth building specific code to implement this feature because it can be directly sold

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
