### ISSUE TITLE
TotK: Feature Request – Old Map Locations

### ISSUE THREAD

**Issue by iZachare** [marcrobledo/savegame-editors#337]
List of each Old Map Location:
1. `-3476, 3514, 0931`
2. `-1649, 3513, 0965`
3. `3295, 3434, 0795`
4. `4269, 3108, 0784`
5. `-3861, 2923, 0748`
6. `-3830, 2715, 0545`
7. `0435, 2196, 2244`
8. `3665, 1795, 0989`
9. `-3438, 1431, 1191`
10. `1811, 1014, 1205`
11. `-3962, 0608, 1709`
12. `-3635, 0467, 1671`
13. `-3377, -0021, 2285`
14. `3200, 0598, 1418`
15. `3168, 0459, 0936`
16. `3693, 0593, 1246`
17. `1663, -0353, 0401`
18. `4752, -0778, 1917`
19. `4659, -0870, 1769`
20. `1852, -0979, 0939`
21. `1766, -1311, 0903`
22. `2645, -1414, 1476`
23. `-1233, -1400, 0989`
24. `-0816, -1591, 0915`
25. `-1348, -1542, 0802`
26. `-1457, -1584, 1221`
27. `-1956, -1810, 1168`
28. `1652, -2191, 0574`
29. `2160, -2592, 1263`
30. `0952, -3113, 0757`
31. `1126, -3274, 0758`

All this data was taken from the TotK interactive map (no this is not an ad): https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
