### ISSUE TITLE
Change Horse's Color?

### ISSUE THREAD

**Issue by bunnynoah** [marcrobledo/savegame-editors#348]
I wanted to know if you could change the color of a horse. Not for the unique horses of course, I just wish to change one of my horse's colors from light brown to dark brown.

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.
You can now choose the horse color, though it's an undocumented combination between the horse ID and the color you choose, so it will be a blind choice until someone decides to document it :-(

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
