### ISSUE TITLE
TOTK Suggestion : Pin the korok asking for help instead the korok icon

### ISSUE THREAD

**Issue by Asia81** [marcrobledo/savegame-editors#362]
Hello, for the carried koroks, would it be possible to pin the korok asking to reach his friend, instead pin the korok icon (the place where its friend is) ?
Because if I go there, there is nothing triggered as long I didn't speak to the korok first, and then I'm searching where this korok is.

**Comment by Asia81** [comment]
That could be easier. The suggestion could also apply to single koroks that has timed plateforms or flowers.

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
