### ISSUE TITLE
Pin all shrines has one pin placed on incorrect layer

### ISSUE THREAD

**Issue by JonJaded** [marcrobledo/savegame-editors#363]
The West Nucleda Sky Crystal - Ukoojisi Shrine has its marker placed on the surface rather than the sky. Coordinates are perfectly fine though!

**Comment by Asia81** [comment]
i had the same problem with some koroks also, pinned in the sky instead of the surface (sorry i forgot to write whicn ones...).

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.
Coordinates in the sourcecode were fine. However, it seems the game has not a fixed value to decide the map you are on (sky/ground/depths). Looks like it depends on your locations as well (for example Gerudo Highlands, which are very high). This means, some manual fixes will be need to be done in our coordinates in order for the editor to choose correctly the map for the pin.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
