### ISSUE TITLE
ToTK: Feature Request: Ability to export current map pin data.

### ISSUE THREAD

**Issue by ApacheThunder** [marcrobledo/savegame-editors#364]
Mainly for those who want to pin all the korok seed locations so they can go pick them up themselves. Doing this usually means sacrificing all your existing map pins. Ability to export/backup this data in some way before doing this would be great for those who want do to that. ;)

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
