### ISSUE TITLE
Bubbulfrogs

### ISSUE THREAD

**Issue by Wee34** [marcrobledo/savegame-editors#366]
I had click for all Bubbulfrogs to be defeated. However I still find bubbulfrog in most of the caves. Do I need to change something else?

**Comment by JonJaded** [comment]
@Karlos007 was wondering if you knew anything we could change in master editor as mentioned in #358 ? Running into the same issue.

I can say though that you have to mark caves in master editor manually as well. I tried `IsGetCaveMasterMedal` but that doesn't seem to be it, and I can't find anything else with `Nushi` under master editor.

**Comment by Karlos007** [comment]
Bubbulfrogs are a bit complex to cheat.

You can compare the flags with this save https://gamebanana.com/mods/450649

DefeatedEnemyNum.Enemy_CaveMaster_000 = 147
ExchangedCaveMasterMedalNum = 147
Nushishop_MedalRemaining = 0
NushiShop_MedalComplete = true
IsGetCaveMasterMedal

there is also a youtube video with all 147 locations

**Comment by Wee34** [comment]
@marcrobledo have this been fix yet?

**Comment by marcrobledo** [comment]
No, but I plan to fix it, that's why I kept the issue open :-)

After finding out how flags for Addison and Sage's Will work, this comes next.

**Comment by marcrobledo** [comment]
Okay, fixed now.
- counter in the savegame editor counts now the defeated CaveMaster actor uids instead of the boolean hashes
- setting all of them as defeated now also marks the actor uids as defeated (in other words: they won't appear in caves anymore)
- setting all of them as defeated set the correct Koltin flags so the quest can be completed
- previous savegames that used the unlock all feature should be able to use it again, thus removing all bubbuls in caves and completing the quest correctly

**Comment by JonJaded** [comment]
You're a genius, thanks a ton!
