### ISSUE TITLE
TotK: [Bug/Mistake] Wrong Location for Aerial Cannon (Yiga Schematic)

### ISSUE THREAD

**Issue by Rajvir8** [marcrobledo/savegame-editors#373]
For some reason this Yiga Schematic pops up on the wrong location consistently, only one that does as of June 26, 2023, ended up going to a list of every Schematic and there location to find the missing one, a little embarrassing that it was relatively close, likely should have realized myself.

Chest is where it is pinning, your location is the correct spot, ID in Screenshot but also correct one is 0130, 2867, -0634, but I've heard before that the compass isn't to useful so I'm not sure if that would help.

![Screenshot (247)](https://github.com/marcrobledo/savegame-editors/assets/17600697/c78bd40f-5a42-45a0-a47f-d323b24dc7fa)

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
