### ISSUE TITLE
[ToTK] Corrections for BubbulFrogs

### ISSUE THREAD

**Issue by CeruleanSky** [marcrobledo/savegame-editors#374]
I went on the Cave/Bubbul Frog tour, I had about 100 already before using the save editor, so I only tested 40 something. 

These hashes are wrong for map pins and I don't think Bubbulfrogs exist for them, they tend to be chasms:
//IsGetCaveMasterMedal
0x29e4a302, //GerudoDesert_0043
0xca24f955, //HyruleRidge_0004
0x6ade83b3, //Lanayru_0050
0x52e5cfba, //Lanayru_0063

These flags are missing in the array and are the correct ones:
IsGetCaveMasterMedal.Well_0043B
IsGetCaveMasterMedal.Zora_Imperial_Palace	
IsGetCaveMasterMedal.ZoraZonauTerminal

Coordinates for the cave entrances can be found from https://objmap-totk.zeldamods.org/ , just search for the suffix, example Well_0043B or Zora_Imperial_Palace .

I think the cave pins just needs the two Zora ones.

**Comment by vincent0408** [comment]
Yeah seconded, I have killed 144 bubbul frogs and these are the last 4 I cannot find

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
