### ISSUE TITLE
add Wolf Link in the Editor?

### ISSUE THREAD

**Issue by snake1978** [marcrobledo/savegame-editors#43]
Would it be possible to add Wolf Link in the Editor? Thank you

**Comment by marcrobledo** [comment]
A while ago, I found a way to successfully inject Wolf Link using savegame editing. But it was not worth, since it needed you to take a wild horse, then edit the savegame. Worst of all, it just disappeared as soon as you entered a shrine or teleported (thus needed to edit the savegame once again in order to use it again).
Use a trainer for this.
