### ISSUE TITLE
899 koroks issue

### ISSUE THREAD

**Issue by Zanza25** [marcrobledo/savegame-editors#59]
Hi, i've been using the web page http://www.marcrobledo.com/savegame-editors/zelda-botw/ and i've added pins for searching koroks myself, but it doesn't add last one (number 900), I don't understand why is this happening I've downloaded your "example savegame" and it works perfectly, but it doesn't work with my savegame, the one i've dumped, I decided complete the last korok automatically with "get all" button but it doesn't work either, continues to happen same thing, web page shows that it has added 0 koroks, and I can't get the last one

this is my file compressed in .zip, i've played a lot this game i would appreciate if you can help me with this.

ver. 1.4.0
DLC ver. 3.0

excuse my english, thank you

[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/1918751/game_data.zip)

**Comment by marcrobledo** [comment]
For some reason your in-game counter got bugged (did you use the Master Editor by any chance?). But do not worry, the unlock koroks seed function is working in your savegame anyway even if you still see 899.
I don't think I can fix it since the editor is working fine, it seems it's related to your savegame.

Anyway, there is a solution though :-)
Just use the [Master Editor](http://www.marcrobledo.com/savegame-editors/zelda-botw-master/), search HiddenKorok_Complete and set it to 900.

**Comment by Zanza25** [comment]
thank you, it worked perfectly
