### ISSUE TITLE
Hyrule compendium completion

### ISSUE THREAD

**Issue by Araraura** [marcrobledo/savegame-editors#61]
Is there a way to instantly fill the Hyrule compendium is master mode with all the stock images? I know that right now the editor can change all captures pictures to stock, but is there a way to unlock the missing images? If not, is it going to be possible in the future?

**Comment by marcrobledo** [comment]
Neither Master Mode or DLC2 have stock photos in the update data (that's why there is no option to buying them in-game).
Adding an option to unlocking them is impossible, since there are no stock photos and user would need to provide their own pics.

**Comment by marcrobledo** [comment]
I might be wrong.

**Comment by Araraura** [comment]
Actually, they do have it, but it's in the dlc/update files, not the actual game

**Comment by marcrobledo** [comment]
Last time I checked I did not found the new pictures. It made sense since you cannot buy the new pics in-game, right? But yeah, looks like they are there after all.
Anyway, I even tried it then and they appeared as black pictures. But I forgot to change a bit, so maybe it's still possible.

You can try it right now in the [Master Editor](http://www.marcrobledo.com/savegame-editors/zelda-botw-master/). Look for these values and change them to:
IsRegisteredPictureBook_Enemy_Golem_Fire_R=checked
IsRegisteredPictureBook_Enemy_SandwormR=checked
IsRegisteredPictureBook_Priest_Boss_Normal=checked
IsRegisteredPictureBook_Weapon_Sword_502 =checked
PictureBookSize_Enemy_Golem_Fire_R=4294967295
PictureBookSize_Enemy_SandwormR=4294967295
PictureBookSize_Priest_Boss_Normal=4294967295
PictureBookSize_Weapon_Sword_502 =4294967295

Let me know if it works!
If it works, then I'll implement them to the normal editor,

**Comment by Araraura** [comment]
Actually.. I can't really do that since I manually replaced the pictures already. My compendium was already completed.

**Comment by marcrobledo** [comment]
Yes, you can do it anyway. Just set all PictureBookSize_* as 4294967295 and it will try to load the stock ones. If it works, then you can delete the *.jpg in your savagem safely. Keep a backup of your savegame, just in case they show up as black pictures.

**Comment by marcrobledo** [comment]
I got little time to try it, and it worked :-)
I'll implement it in the following weeks.

**Comment by marcrobledo** [comment]
Fixed ina4e25434b75ad0d78dec9c6a9a5d803dae2ca854
