### ISSUE TITLE
Item selector does not appear after adding an item

### ISSUE THREAD

**Issue by illestxAsianzZ** [marcrobledo/savegame-editors#62]
Whenever I try to add items it doesn't give me an option to pick one it just generates fruit for me

**Comment by Zm0n** [comment]
+1. 

Tried in Chrome, Firefox, and Edge to see if it was a browser issue. The save editor was working fine early this morning, and now it's just adding fruit when you add an item. I don't see any new commits, so it's a bit odd.

**Comment by bad1dea** [comment]
When you "Add Item" it'll add it to the current slot/area you're viewing in browser.

Click on the Item (Picture) of the item you added, and a popup will appear to allow you to change what item it is.. if it's currently an Apple and you change it to a Shield it will move the item to appropriate section of items.

**Comment by illestxAsianzZ** [comment]
If you do that you won't be able to modify the modifier for said weapon

**Comment by marcrobledo** [comment]
I changed the way items are added in order to make it easier and quickier to add a lot of items (issue #60). The advantage is that you can now add items sequentally.
i.e.: add an item (it will be an apple at first). Change it to your desired weapon, and the next item you add will be the next weapon.

Yes, you cannot edit modifiers. But you weren't able to do it before I made this change anyway.
I'll try to work on it this summer (I hope I recall :-P).

The way weapons and modifiers are stored and how they are sorted in the savegame are not implemented in the editor yet, so you cannot edit modifiers in newly created weapons.
Quick solution: put your savegame, start playing and savegame so the game automatically resorts items (and you will then be able to edit modifiers in the editor).
But if you really want to add lots of weapons, just fill your inventory with lots weapons in-game, then you will be able to edit them and their modifiers in the editor.
