### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Calebbrady01** [marcrobledo/savegame-editors#89]
Can someone please inform me how to use this with my switch, I've tried to look it up but can not find any guides

**Comment by Conan179** [comment]
No, only this Games, nothing on Switch:
Hyrule Warriors (**Wii U**)
The legend of Zelda: Breath of the wild (**Wii U**)
Kid Icarus: Uprising (**3DS**)
Team Kirby Clash Deluxe(**3DS**)
Picross 3D Round 2 (**3DS**)
Pokémon Picross (**3DS**)
Pokémon Shuffle (**3DS**)
Rhythm Paradise Megamix (**3DS**)
StreetPass Mii Plaza (**3DS**)

**Comment by marcrobledo** [comment]
The editor works with the Switch version too. I've updated the readme file.

In order to use the editor you need to extract the savegame. You will need a Switch running a CFW and then you can use github/FlagBrew/Checkpoint to extract and inject savegame.
Sorry, this is not the place to ask for how to mod a Switch console.
