### ISSUE TITLE
Request: add registered horse editing support [Breath of the Wild]

### ISSUE THREAD

**Issue by InacioNeto** [marcrobledo/savegame-editors#9]
Is it possible for you to add support to see/edit/add horses you have registered in the stables?

**Comment by ggouki** [comment]
Here are the byte sequences that determine the beginning of each of the horse related tables in the savegame in case you don't have them yet @marcrobledo 

33 3A 67 8A		HORSE SADDLE
61 4C 41 63		HORSE REINS
7B 74 27 F3		HORSE NAME
9C 6B 85 05		SIMPLE INDICATOR	
C2 47 00 CC		HORSE TYPE
E1 A0 CA 54		HORSE BOND (MAX 3F 80)

HORSE BOND is not needed by the way when adding a horse because it defaults to 0, but nice to have

but the others are essential when adding or it won't work

would be cool if you could add it to the editor

**Comment by marcrobledo** [comment]
@ggouki does changing horse type string also changes its parameters (speed, etc.)?

**Comment by ggouki** [comment]
@marcrobledo yes, horse type determines the looks and stats, they're always the same depending on the type, and one of them happens to be the 'epona type' and that seems to be all there is to it

seems like the table at 9C 6B 85 05 is for horse manes? but they're always the same (tied to type) so i assume it's either a feature that didn't make it into the game or will in the future (DLC)

there is also determining values for whether or not a horse is in the stable or in the outside world somewhere, not sure its in one of those tables or in its own ( i think the former ) but it doesn't seem relevant to adding or removing horses

**Comment by marcrobledo** [comment]
Horse editor has been added, thank you @ggouki ! :-)
